android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true

# Performance Optimization
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.daemon=true

# Fix for "The process cannot access the file because it is being used by another process"
kotlin.incremental=false

# Experimental removals (cleanup)
android.defaults.buildfeatures.resvalues=true
android.enableAppCompileTimeRClass=false
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false
